spring:
  datasource:
    username: ${spring.datasource.username}
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
  application:
    name: companies-crud-ms
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
server:
  servlet:
    context-path: /companies-crud
#    companies-crud
  port: 0
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

