spring.application.name=companies-crud-ms

# Zona horaria de aplicacion
spring.jackson.time-zone=America/Mexico_City

# Conexion a base de datos
spring.datasource.url=jdbc:postgresql://localhost:5431/companies
spring.datasource.username=root
spring.datasource.password=admin

# Configuracion de microservicio
server.servlet.context-path=/companies-crud