spring:
  jackson:
    time-zone: America/Mexico_City
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5431/companies
    password: admin
  application:
    name: companies-crud-ms
server:
  servlet:
    context-path: /companies-crud
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
